export const MOCK_DATA = {
  stats: {
    suratMasuk: 125,
    suratKeluar: 87,
    totalArsip: 542,
  },
  recentActivities: [
    { id: 1, text: "Surat masuk baru ditambahkan: Undangan Rapat Pleno Rekapitulasi", time: "10 menit yang lalu", type: "surat_masuk" },
    { id: 2, text: "Surat keluar diperbarui: Keputusan Penetapan DPT Pemilu 2026", time: "1 jam yang lalu", type: "surat_keluar" },
    { id: 3, text: "Arsip baru ditambahkan: Berita Acara Serah Terima Kotak Suara", time: "3 jam yang lalu", type: "arsip" },
    { id: 4, text: "Data pegawai diperbarui: Ahmad Fauzi, S.Sos (Subbag Teknis)", time: "Kemarin, 14:30", type: "pegawai" },
    { id: 5, text: "Nota Dinas diterbitkan: Permohonan Fasilitas Rapat Koordinasi", time: "2 hari yang lalu", type: "nota" },
  ],
  dokumenInternalTerbaru: [
    { id: "DI-001", title: "Laporan Realisasi Anggaran Triwulan I 2026", category: "Keuangan, Umum dan Logistik", date: "24 Juni 2026", size: "2.4 MB" },
    { id: "DI-002", title: "Analisis Data Pemilih Potensial TPS Khusus", category: "Perencanaan, Data dan Informasi", date: "22 Juni 2026", size: "4.1 MB" },
    { id: "DI-003", title: "SK Pembentukan Tim Sosialisasi Pilkada Serentak", category: "Parhubmas dan SDM", date: "20 Juni 2026", size: "1.8 MB" },
    { id: "DI-004", title: "Kajian Hukum Putusan Bawaslu Kota Banjarmasin", category: "Teknis Penyelenggaraan Pemilu dan Hukum", date: "18 Juni 2026", size: "3.2 MB" },
  ],
  suratMasukDisposisiOptions: ["KUL", "PERDATIN", "PARHUBMAS & SDM", "TEKNIS & HUKUM"],
  suratMasukDitujukanOptions: ["KETUA", "SEKRETARIS"],
  kodeArsipOptions: [
    { code: "PP.06", label: "PP.06 (Narasumber)" },
  ],
  suratMasukList: [
    {
      id: "SM-2026-001",
      nomorUrut: 1,
      nomorAgenda: "1",
      tanggal: "2026-01-02",
      alamatPengirim: "UIN Antasari Banjarmasin",
      tanggalSurat: "2026-01-02",
      nomorSurat: "139/S/P/PP-PBPM-KPM/EMA-U/UN-A/I/2026",
      perihal: "Permohonan Narasumber Pengabdian Bagi Pemuda Mahasiswa",
      disposisi: "PARHUBMAS & SDM",
      ditujukan: "KETUA",
      kodeArsip: "PP.06",
      srikandi: true,
    },
    {
      id: "SM-2026-002",
      nomorUrut: 2,
      nomorAgenda: "2",
      tanggal: "2026-01-05",
      alamatPengirim: "KPU Provinsi Kalimantan Selatan",
      tanggalSurat: "2026-01-04",
      nomorSurat: "001/KPU-Prov.Kalsel/I/2026",
      perihal: "Undangan Koordinasi Logistik Pemilu 2026",
      disposisi: "KUL",
      ditujukan: "SEKRETARIS",
      kodeArsip: "PP.06",
      srikandi: true,
    },
    {
      id: "SM-2026-003",
      nomorUrut: 3,
      nomorAgenda: "3",
      tanggal: "2026-01-08",
      alamatPengirim: "Bawaslu Kota Banjarmasin",
      tanggalSurat: "2026-01-07",
      nomorSurat: "045/Bawaslu-BJM/I/2026",
      perihal: "Penyampaian Hasil Pengawasan Coklit Data Pemilih",
      disposisi: "TEKNIS & HUKUM",
      ditujukan: "KETUA",
      kodeArsip: "PP.06",
      srikandi: false,
    },
    {
      id: "SM-2026-004",
      nomorUrut: 4,
      nomorAgenda: "4",
      tanggal: "2026-01-12",
      alamatPengirim: "Walikota Banjarmasin",
      tanggalSurat: "2026-01-11",
      nomorSurat: "112/Pemko-BJM/I/2026",
      perihal: "Fasilitas Ruangan Rapat Pleno Rekapitulasi",
      disposisi: "KUL",
      ditujukan: "SEKRETARIS",
      kodeArsip: "PP.06",
      srikandi: true,
    },
    {
      id: "SM-2026-005",
      nomorUrut: 5,
      nomorAgenda: "5",
      tanggal: "2026-01-15",
      alamatPengirim: "Polresta Banjarmasin",
      tanggalSurat: "2026-01-14",
      nomorSurat: "012/Polresta-BJM/I/2026",
      perihal: "Koordinasi Pengamanan Gudang Logistik KPU",
      disposisi: "PERDATIN",
      ditujukan: "KETUA",
      kodeArsip: "PP.06",
      srikandi: false,
    },
  ],
  suratKeluarList: [
    { id: "SK-2026-001", nomor: "123/KPU-BJM.065/VI/2026", tujuan: "PPK Se-Kota Banjarmasin", perihal: "Instruksi Pemutakhiran Data Pemilih Berkelanjutan", tanggal: "2026-06-25", status: "Terkirim" },
    { id: "SK-2026-002", nomor: "124/KPU-BJM.065/VI/2026", tujuan: "Pimpinan Partai Politik Peserta Pemilu", perihal: "Undangan Rapat Sinkronisasi Dana Kampanye", tanggal: "2026-06-23", status: "Terkirim" },
    { id: "SK-2026-003", nomor: "125/KPU-BJM.065/VI/2026", tujuan: "Kepala Badan Kesbangpol", perihal: "Laporan Kegiatan Pendidikan Pemilih Pemula", tanggal: "2026-06-21", status: "Draft" },
    { id: "SK-2026-004", nomor: "126/KPU-BJM.065/VI/2026", tujuan: "KPU Provinsi Kalimantan Selatan", perihal: "Laporan Bulanan Keuangan & Logistik", tanggal: "2026-06-18", status: "Terkirim" },
  ],
  notaDinasList: [
  { id: "ND-2026-001", noUrut: 1, kodeArsip: "PP.06", jenisNaskah: "ND", tanggal: "2026-06-12", alamatTujuan: "Sekretaris KPU Kota Banjarmasin", perihal: "Permohonan Persetujuan Anggaran Kegiatan", keterangan: "Menunggu tanda tangan Sekretaris", nomor: "1/PP.06-ND/6371/2026", bagian: "Komisioner" },
  { id: "ND-2026-002", noUrut: 1, kodeArsip: "PP.06", jenisNaskah: "ND", tanggal: "2026-06-14", alamatTujuan: "Subbagian Teknis & Hukum", perihal: "Koordinasi Persiapan Bimtek PPK", keterangan: "", nomor: "1/PP.06-ND/6371/2026", bagian: "KUL" },
  ],
  beritaAcaraList: [
  { id: "BA-2026-001", noUrut: 1, kodeArsip: "PP.06", tanggal: "2026-06-05", alamatTujuan: "PPK Se-Kota Banjarmasin", perihal: "Berita Acara Serah Terima Kotak Suara", subbagId: "SUB-TPH", penanggungJawab: "M. Rizki Pratama, S.IP", nomor: "1/PP.06-BA/6371/2026", bagian: "Ketua", arsipFileName: "ba-serah-terima.pdf", arsipFileUrl: "" },
  { id: "BA-2026-002", noUrut: 1, kodeArsip: "PP.06", tanggal: "2026-06-08", alamatTujuan: "Sekretariat KPU Kota Banjarmasin", perihal: "Berita Acara Rapat Koordinasi Internal", subbagId: "SUB-KUL", penanggungJawab: "Siti Rahmah, S.Sos", nomor: "1/PP.06-BA/6371/2026", bagian: "Sekretaris", arsipFileName: "ba-rakor.pdf", arsipFileUrl: "" },
  ],
  legalisirList: [
  { id: "LG-2026-001", noUrut: 1, nomorAgenda: "45", tanggalLegalisir: "2026-06-20", tandaTanganLegalisir: "Drs. H. Rusdiansyah, M.AP", instansiParpol: "DPC Partai Merah Putih Kota Banjarmasin", perihal: "Legalisir Salinan SK Kepengurusan Partai", tanggalPenyerahan: "2026-06-22", diserahkanKepada: "Ahmad Fauzi (Sekretaris DPC)", arsipFileName: "sk-kepengurusan-legalisir.pdf" },
  { id: "LG-2026-002", noUrut: 2, nomorAgenda: "46", tanggalLegalisir: "2026-06-18", tandaTanganLegalisir: "Siti Rahmah, S.Sos", instansiParpol: "PPK Kecamatan Banjarmasin Tengah", perihal: "Legalisir Salinan Berita Acara Rekapitulasi", tanggalPenyerahan: "2026-06-19", diserahkanKepada: "Muhammad Yusuf (Ketua PPK)", arsipFileName: "ba-rekap-legalisir.pdf" },
  ],
  skList: [
  { id: "SK-2026-001", noUrut: 1, nomorSk: "12/SK/KPU-Bjm/VI/2026", tanggal: "2026-06-10", perihal: "Penetapan Tim Kerja Persiapan Pemilihan", skOleh: "Ketua", subbagId: "SUB-TPH", arsipFileName: "sk-tim-kerja.pdf", arsipFileUrl: "" },
  { id: "SK-2026-002", noUrut: 2, nomorSk: "13/SK/KPU-Bjm/VI/2026", tanggal: "2026-06-14", perihal: "Penunjukan Pengelola Keuangan Kegiatan", skOleh: "Sekretaris", subbagId: "SUB-KUL", arsipFileName: "sk-pengelola-keuangan.pdf", arsipFileUrl: "" },
  ],
  bukuAgendaCategories: [
    { name: "Surat Masuk", count: 125, path: "surat-masuk", desc: "Pencatatan dan disposisi surat yang diterima instansi" },
    { name: "Surat Keluar", count: 87, path: "surat-keluar", desc: "Arsip dan penomoran surat keluar instansi" },
    { name: "Surat Tugas & SPD Ketua", count: 34, path: "surat-tugas-ketua", desc: "Surat perintah perjalanan dinas dan tugas Ketua KPU" },
    { name: "Surat Tugas & SPD Sekretaris", count: 42, path: "surat-tugas-sekretaris", desc: "Surat perintah tugas dan perjalanan dinas Sekretariat" },
    { name: "Nota Dinas", count: 68, path: "nota-dinas", desc: "Komunikasi kedinasan internal antar subbagian" },
    { name: "Berita Acara", count: 56, path: "berita-acara", desc: "Dokumentasi resmi keputusan dan serah terima" },
    { name: "Legalisir", count: 110, path: "legalisir", desc: "Pencatatan pengesahan dokumen dan salinan sah" },
    { name: "Surat Keputusan", count: 29, path: "surat-keputusan", desc: "SK Pleno, SK Sekretaris, dan ketetapan resmi" },
    { name: "SOP", count: 18, path: "sop", desc: "Standar Operasional Prosedur pelayanan administrasi" },
    { name: "MOU", count: 12, path: "mou", desc: "Nota kesepahaman kerjasama antar lembaga" },
  ],
  dokumenInternalSections: [
    { id: "keuangan", title: "Keuangan, Umum dan Logistik", count: 145, desc: "Laporan anggaran, inventaris, pengadaan barang dan logistik pemilu" },
    { id: "perencanaan", title: "Perencanaan, Data dan Informasi", count: 198, desc: "Data pemilih, dpt, pemetaan TPS, dan renstra instansi" },
    { id: "parhubmas", title: "Parhubmas dan SDM", count: 112, desc: "Kepegawaian, diklat, partisipasi masyarakat, dan hubungan media" },
    { id: "teknis", title: "Teknis Penyelenggaraan Pemilu dan Hukum", count: 87, desc: "Pencalonan, kampanye, pemungutan suara, dan kajian hukum" },
  ],
  klasifikasiArsipList: [
    { code: "SUB-01", name: "Penyelenggaraan Pemilu & Pemilihan", type: "Substantif", desc: "Tahapan pemilu, pemutakhiran data pemilih, logistik pemilu" },
    { code: "SUB-02", name: "Hukum & Pengawasan", type: "Substantif", desc: "Sengketa pemilu, penanganan pelanggaran, dan produk hukum" },
    { code: "FAS-01", name: "Kepegawaian & SDM", type: "Fasilitatif", desc: "Mutasi, cuti, kenaikan pangkat, diklat pegawai" },
    { code: "FAS-02", name: "Keuangan & Anggaran", type: "Fasilitatif", desc: "DIPA, SPJ, Honorarium badan adhoc, pengadaan" },
    { code: "FAS-03", name: "Umum & Perlengkapan", type: "Fasilitatif", desc: "Inventaris kantor, pemeliharaan gedung, dan kearsipan" },
  ],
  masterDataPegawai: [
    { nip: "198205122005011002", name: "Drs. H. Rusdiansyah, M.AP", jabatan: "Sekretaris KPU", subbag: "Sekretariat", status: "Aktif" },
    { nip: "198509202010012001", name: "Siti Rahmah, S.Sos", jabatan: "Kasubbag Keuangan, Umum & Logistik", subbag: "Keuangan & Umum", status: "Aktif" },
    { nip: "199011152014031004", name: "Ahmad Fauzi, S.Kom", jabatan: "Pranata Komputer Ahli Muda", subbag: "Perencanaan & Data", status: "Aktif" },
    { nip: "198803222012122003", name: "Dewi Lestari, SH", jabatan: "Kasubbag Hukum & SDM", subbag: "Parhubmas & SDM", status: "Aktif" },
    { nip: "199201052018021001", name: "M. Rizki Pratama, S.IP", jabatan: "Staf Teknis Pemilu", subbag: "Teknis & Hukum", status: "Aktif" },
  ],
  masterDataSubbagian: [
    { code: "SUB-KUL", name: "Subbagian Keuangan, Umum dan Logistik", kepala: "Siti Rahmah, S.Sos", pegawaiCount: 8 },
    { code: "SUB-PDI", name: "Subbagian Perencanaan, Data dan Informasi", kepala: "Ahmad Fauzi, S.Kom", pegawaiCount: 6 },
    { code: "SUB-PSD", name: "Subbagian Parhubmas dan SDM", kepala: "Dewi Lestari, SH", pegawaiCount: 7 },
    { code: "SUB-TPH", name: "Subbagian Teknis Penyelenggaraan Pemilu dan Hukum", kepala: "M. Rizki Pratama, S.IP", pegawaiCount: 9 },
  ],
  masterDataPejabat: [
    { name: "Dr. Hj. Anna Salsabila, M.Si", jabatan: "Ketua KPU Kota Banjarmasin", tmt: "2023-01-15" },
    { name: "Drs. H. Rusdiansyah, M.AP", jabatan: "Sekretaris KPU Kota Banjarmasin", tmt: "2021-06-10" },
    { name: "H. M. Noor, SE", jabatan: "Anggota Divisi Teknis Penyelenggaraan", tmt: "2023-01-15" },
    { name: "Dr. Nurul Hidayah, M.Pd", jabatan: "Anggota Divisi Perencanaan & Data", tmt: "2023-01-15" },
  ],
  masterDataJenisNaskah: [
    { kode: "ND", nama: "Nota Dinas", ket: "Internal antar subbagian" },
    { kode: "ST", nama: "Surat Tugas", ket: "Perintah pelaksanaan tugas kedinasan" },
    { kode: "SPD", nama: "Surat Perjalanan Dinas", ket: "Perjalanan dinas jabatan" },
    { kode: "SK", nama: "Surat Keputusan", ket: "Ketetapan resmi lembaga" },
    { kode: "BA", nama: "Berita Acara", ket: "Pernyataan peristiwa/serah terima" },
  ],
  masterDataWilayah: [
    { kode: "63.71.01", kecamatan: "Banjarmasin Selatan", kelurahanCount: 12 },
    { kode: "63.71.02", kecamatan: "Banjarmasin Timur", kelurahanCount: 9 },
    { kode: "63.71.03", kecamatan: "Banjarmasin Barat", kelurahanCount: 9 },
    { kode: "63.71.04", kecamatan: "Banjarmasin Tengah", kelurahanCount: 12 },
    { kode: "63.71.05", kecamatan: "Banjarmasin Utara", kelurahanCount: 10 },
  ],
  defaultPermissions: {
    keuangan: true,
    perencanaan: true,
    parhubmas: true,
    teknis: false,
  }
};
